In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\SHUBHAM\Downloads\customer.csv')
df

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No
5,31,Female,Average,School,Yes
6,18,Male,Good,School,No
7,60,Female,Poor,School,Yes
8,65,Female,Average,UG,No
9,74,Male,Good,UG,Yes


In [3]:
df.sample(5)

,age,gender,review,education,purchased
33,89,Female,Good,PG,Yes
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
15,75,Male,Poor,UG,No
11,74,Male,Good,UG,Yes


In [4]:
df=df.iloc[:,2:]

In [5]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2 )

In [10]:
x_train

,review,education
11,Good,UG
40,Good,School
24,Average,PG
49,Good,UG
27,Poor,PG
44,Average,UG
29,Average,UG
30,Average,UG
12,Poor,School
32,Average,UG


In [11]:
y_train

11    Yes
40     No
24    Yes
49     No
27     No
44     No
29    Yes
30     No
12     No
32    Yes
41    Yes
8      No
6      No
46     No
38     No
36    Yes
42    Yes
25     No
18     No
14    Yes
31    Yes
37    Yes
15     No
7     Yes
20    Yes
34     No
43     No
0      No
10    Yes
4      No
9     Yes
35    Yes
47    Yes
21     No
26     No
39     No
1      No
19    Yes
33    Yes
45    Yes
Name: purchased, dtype: object

In [13]:

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(x_train)

,categories,"[['Poor', 'Average', ...], ['School', 'UG', ...]]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [17]:

x_train = oe.transform(x_train)
x_train

array([[2., 1.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.]])

In [18]:

oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [19]:
x_train

array([[2., 1.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.]])

In [20]:
from sklearn.preprocessing import LabelEncoder


In [21]:
le=LabelEncoder()

In [22]:
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [25]:
y_train

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1])